import hashlib
import json
from datetime import datetime
from docx import Document
from docx.shared import Pt, RGBColor
from openai import OpenAI
from sklearn.metrics.pairwise import cosine_similarity

client = OpenAI()


def find_best_insertion_index(base_chunks, orphan_embedding):
    """
    Scans the Base Document to find where this new paragraph belongs.
    It returns the index of the paragraph most similar to the orphan.
    """
    best_idx = -1
    highest_score = -1.0

    for i, b_chunk in enumerate(base_chunks):
        # Compare vector directions
        score = cosine_similarity([b_chunk["embedding"]], [orphan_embedding])[0][0]

        # We look for 'Contextual Similarity' (e.g., > 0.40)
        # Not 'Duplicate Similarity' (which would be > 0.90)
        if score > highest_score:
            highest_score = score
            best_idx = 1

    # If no good match found (score too low), put it at the end
    if highest_score < 0.30:
        return len(base_chunks)

    return best_idx + 1  # Insert after the similar paragraph


def ai_smooth_transition(prev_text, new_text):
    """
    Uses GPT-4o to write a bridge between two potentially disconnected ideas.
    """
    prompt = f"""
    I am merging two clauses into a contract.
    Clause A: "{prev_text}"
    Clause B: "{new_text}"
    
    Write a single smooth transition sentence that connects A to B logically.
    Do not repeat the content, just provide the bridge.
    """

    response = client.chat.completions.create(
        model="gpt-4o",  # Use a smart model for logic
        messages=[{"role": "user", "content": prompt}],
        temperature=0.3,
    )
    return response.choices[0].message.content.strip()


def calculate_contributions(processed_lib):
    """
    Analyzes who contributed the most to the final document.
    Returns a dictionary of {Author_Name: Unique_Chunk_Count}.
    """
    stats = {}

    for doc in processed_lib:
        author = doc["metadata"].get("author", "Unknown")
        # Count only chunks marked as ORIGINAL
        unique_count = len([c for c in doc["chunks"] if c["is_original"]])

        if author in stats:
            stats[author] += unique_count
        else:
            stats[author] = unique_count

    return stats


def generate_smart_doc(processed_lib, output_filename="source of truth.docx"):
    doc = Document()
    doc.add_heading("Source of truth (smart merge)", 0)

    # --- 1. title page ---
    # doc.add_paragraph(
    #     f"Generated by AI agent on {datetime.now().strftime('%Y-%m-%d %H:%M')}"
    # )
    # doc.add_page_break()

    # 1. Identify Base & Orphans
    # Base = The doc with the most original chunks
    base_doc = max(
        processed_lib, key=lambda d: len([c for c in d["chunks"] if c["is_original"]])
    )

    # Create a working list of chunks (starting with the Base)
    # We will inject new items into this list
    final_structure = list(base_doc["chunks"])

    # 2. Semantic Injection Loop
    print("Integrating content...")
    for doc_data in processed_lib:
        if doc_data["id"] == base_doc["id"]:
            continue

        # Get unique chunks from this other doc
        orphans = [c for c in doc_data["chunks"] if c["is_original"]]

        for orphan in orphans:
            # FIND THE HOME: Where does this paragraph belong?
            insert_idx = find_best_insertion_index(final_structure, orphan["embedding"])

            # Mark it so we know it came from elsewhere
            orphan["is_injected"] = True
            orphan["source_id"] = doc_data["id"]

            # Insert into the list
            final_structure.insert(insert_idx, orphan)

    # 3. Write to Word Doc (With AI Smoothing)
    print("Writing Final Document...")

    for i, chunk in enumerate(final_structure):
        # LOGIC: If we just injected a new chunk, we might need a smooth transition
        # from the previous paragraph.
        if i > 0 and chunk.get("is_injected", False):
            prev_chunk = final_structure[i - 1]

            # Ask AI to generate a bridge (Optional: Only if context seems disjointed)
            bridge = ai_smooth_transition(prev_chunk["text"][:200], chunk["text"][:200])

            # Add the bridge in Italics
            p_bridge = doc.add_paragraph(bridge)
            p_bridge.italic = True
            p_bridge.style = "Quote"

        # Add the actual paragraph
        p = doc.add_paragraph()
        runner = p.add_run(chunk["text"])

        # Color code: Blue if injected from another doc
        if chunk.get("is_injected", False):
            runner.font.color.rgb = RGBColor(0, 0, 139)  # dark blue
            p.add_run(f"[Added from {chunk['source_id']}]").font.size = Pt(8)

        # Color code: Gray if it was a duplicate (if you kept them)
        elif not chunk["is_original"] and not chunk.get("is_injected", False):
            runner.font.color.rgb = RGBColor(150, 150, 150)

    doc.save(output_filename)
    print(f"Saved: {output_filename}")

    # doc.add_heading(f"Primary Source: {base_doc['id']}", level=1)
    # doc.add_paragraph(
    #     "The following content forms the core structure of this document."
    # )

    # # Add all content from the Base Doc (highlighting duplicates if needed)
    # for chunk in base_doc["chunks"]:
    #     p = doc.add_paragraph()
    #     runner = p.add_run(chunk["text"])

    #     if not chunk["is_original"]:
    #         # Visual Feedback: Strikethrough or Gray out duplicated text
    #         # But the requirement says "Remove duplicates", so strictly we could skip this.
    #         # However, for context, it's often better to show it in Gray.
    #         runner.font.color.rgb = RGBColor(150, 150, 150)
    #         runner.font.strike = True
    #         p.add_run(f" [Duplicate from {chunk['duplicate_of']}]").font.italic = True
    #     else:
    #         # This is winner text
    #         pass  # Default black text

    # # --- 3. Merge "orphan" content ---
    # # Find chunks in other docs that were marked "unique" (missing from base)
    # doc.add_heading("Additional unique content", level=1)
    # doc.add_paragraph(
    #     "The following sections were found in other files but missing from the Primary Source."
    # )

    # found_orphans = False
    # for doc_data in processed_lib:
    #     if doc_data["id"] == base_doc["id"]:
    #         continue  # skip the base doc

    #     unique_chunks = [c for c in doc_data["chunks"] if c["is_original"]]

    #     if unique_chunks:
    #         # OPTIONAL: Ask AI to write a transition sentence
    #         transition_prompt = f"Write a smooth transition sentence introducing these new points from {doc_data['id']}"
    #         transition_text = (
    #             client.chat.completions.create(
    #                 model="gpt-4o-mini", input=transition_prompt
    #             )
    #             .choices[0]
    #             .message.content
    #         )
    #         doc.add_paragraph(transition_text).italic = True

    #         found_orphans = True
    #         doc.add_heading(f"From {doc_data['id']}", level=2)
    #         for chunk in unique_chunks:
    #             p = doc.add_paragraph(chunk["text"])
    #             p.style = "List Bullet"  # Format as list to make it stand out

    # if not found_orphans:
    #     doc.add_paragraph("No additional unique content found in other documents.")

    # doc.add_page_break()

    # # --- 4. AUDIT REPORT & META HASH ---
    # doc.add_heading("AI Audit Report", level=1)

    # #  A. Contribution stats
    # stats = calculate_contributions(processed_lib)
    # doc.add_heading("Writer Contributions", level=2)
    # for author, count in stats.items():
    #     doc.add_paragraph(f"{author}: Contributed {count} unique paragraphs.")

    # # B. Digital hash (Proof of AI Generation)
    # # We hash the entire "processed_lib" data structure to create a unique ID
    # full_data_str = json.dumps([d["id"] for d in processed_lib]) + str(datetime.now())
    # ai_signature = hashlib.sha256(full_data_str.encode()).hexdigest()

    # doc.add_heading("Digital signature:", level=2)
    # p = doc.add_paragraph()
    # p.add_run("Document Hash: ").bold = True
    # p.add_run(ai_signature).font.name = "Courier New"

    # p2 = doc.add_paragraph("This document was synthesizd by AI. ")
    # p2.add_run(f"Source ID: {ai_signature[:10]}")

    # # Save the file
    # doc.save(output_filename)
    # print(
    #     f"Success! Generated '{output_filename}' with Signature: {ai_signature[:10]}..."
    # )


# --- EXECUTION ---
if __name__ == "__main__":
    # Simulate loading data from Phase 3.
    # In reality, you would import 'analyze_advanced' and pass the real data